Plant.create(name: "Dandelion", genus: "Taraxacum officinale", 
description: "Invasive weed. Perennial herbaceous plant. It has simple and basal, entire or lobed leaves forming a rosette above the central taproot. The flower heads are 2 - 5 cm in diameter and are yellow to orange colored. They open in the daytime and close at night. Flower heads mature into spherical seed heads that look like whimsical puff balls. Each contains many single-seeded fruits called achenes. Each seed is attached to a pappus of fine hairs, which enable wind-aided dispersal over long distance.", 
medicinal_uses: "Chock full of vitamins A, B, C, and D, as well as minerals such as iron, potassium, and zinc.  In the past, dandelion roots and leaves were used to treat liver problems. Native Americans also boiled dandelion in water and took it to treat kidney disease, swelling, skin problems, heartburn, and upset stomach. In traditional Chinese medicine, dandelion has been used to treat stomach problems, appendicitis, and breast problems, such as inflammation or lack of milk flow. In Europe, it was used in remedies for fever, boils, eye problems, diabetes, and diarrhea. Today, the roots are mainly used to stimulate the appetite, and for liver and gallbladder problems. Dandelion leaves are used as a diuretic to help the body get rid of too much fluid." ,
utilitarian_uses: "Dandelions flowers can be used like Chamomile or Marigolds to give light colored hair a 'Golden Glow'",
edible_parts_preparation: "Both the leaves and flower can be eaten. They both can be used raw in salads. Dandelions can take a light saute. They have a bitte taste so pairing it with dried fruit, berries, or a balsamic vinegrate will make them more appetizing",
sources: "http://en.wikipedia.org/wiki/Dandelion , http://umm.edu/health/medical/altmed/herb/dandelion")
Plant.create(name: "Mugwort", genus: "Artemisia vulgaris" , 
description: "Invasive weed. A perennial weed. It can grow to 4 ft tall, but usually remains around 1 or 2 ft high. It's flower branch towards the top into many spikes of small greenish/purplish flowers. The leaves are alternate, green on the top and white and fuzzy on the bottom. The lower leaves are finely dissected with pointed lobes, while the upper leaves usually have three or so lobes, some of the smallest near to the top being linear.",
medicinal_uses: "Mugwort has been used by many as an emmenagogue, meaning to stimulate menstruation, taken by those with irregular or suppressed menses. It has been suggested that mugwort stimulates the uterus, which agrees with some of the other uses of mugwort as a tonic during labor and to relieve menstrual cramps. Because of its ability to induce menstruation, it has also been used as an abortifacient (to induce miscarriage). It has also been used for epilepsy, colds, fevers, bronchitis, colic, sciatica, kidney ailments, and as a diuretic, diaphoretic, appetite stimulent, and nerve tonic. The volatile oil in the leaves make a good remedy for indigestion, upset stomachs, and other stomach ailments. Research shows it may lower blood sugar." ,
utilitarian_uses: "Used to repel insects, either by hanging the plant around the home, or by applying the tea to your skin. Place sachets of mugwort leaves in closets or bureau drawers to keeps moths away from your clothes. The fuzz from the underside of the leaves can be used as tinder for starting fires. Great for smudging. ",
edible_parts_preparation: "A tea can be made from the leaves and flowers, and the leaves are also sometimes used as a spice, usually with meat dishes. Mugwort was once used to flavor beer." ,
warnings: "One of mugwort's main chemicals is thujone, which contributes to the medicinal properties, but can also be toxic in large doses or over a long period of time, so use with caution. Due to its ability to stimulate menstruation, it has the potential to cause miscarriages and should not be used during pregnancy. If you intend to use it to cause miscarriage, consult a doctor first because the safety of this method has not been established. Also, the leaves may cause dermatitis in some people." ,
sources: "http://www.nyctophilia.net/plants/mugwort.htm")
Plant.create(name: "Amaranth a.k.a. Pigweed", genus: "Amaranthus",
description: "A perennial plant. It is moderately tall, broad-leafed, bushy type of plant that grows about six feet in height and produces a brightly colored flowery head containing a very large number of seeds. It's leaves are green, ovate, and have a bit of wave to their edges. It's flowers are inflorescent meaning they grow in tight long spike clusters and are anywhere from bright purple, red to yellow. These seeds are the amaranth grains found in amaranth cereal and flour. Amaranth is a member of the Chenopodiaceae family of plants and therefore is a relative of beets, Swiss chard, spinach, and quinoa. " ,
medicinal_uses: "Seeds are 16% protein with a 90% bio-availability. High in Calcium, Magnesium, vitamin B-6, Iron, and is the only grain known to man with Vitamin C. It's leaves are diuretic and purgative, and are used in poultices (fresh or as dried powder) to treat inflammations, boils and abscesses, gonorrhoea, orchitis and haemorrhoids.
In Côte d’Ivoire leaf sap is used as an eye wash to treat eye infections and for treating convulsions and epilepsy in children.
In Nigeria an infusion of the whole plant is used to purify the blood and the pounded root is applied against dysentery. I In DR Congo the sap is said to act as a vermifuge, being effective against filaria, as an emmenagogue and to relieve heart troubles. The leaves are believed to have febrifugal properties.",
utilitarian_uses: "Ash of these plants is rich in soda and is used to make soap."
edible_parts_preparation: "The young leaves (before they go to flower) can be eaten stewed or boiled in soup, seed can be made to porridge or  ground into flour for baking, mature roots can be eaten in a stew or stir-fried",
sources: "http://www.theurbanabo.com/urban_plants.php?pid=23 , http://whfoods.org/genpage.php?tname=dailytip&dbid=231, http://ourworld.unu.edu/en/rethinking-a-weed-the-truth-about-amaranth.")